/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cmm.compiler.view;

import com.mycompany.cmm.compiler.view.LexerParser; // Se der erro, verifique o pacote
import com.mycompany.cmm.compiler.model.Token;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import org.fife.ui.rsyntaxtextarea.RSyntaxTextArea;
import org.fife.ui.rsyntaxtextarea.SyntaxConstants;
import org.fife.ui.rtextarea.RTextScrollPane;

/**
 *
 * @author caiof
 */
public class CMMCompilerFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CMMCompilerFrame.class.getName());

    private RSyntaxTextArea textArea;
    private LexerParser lexerParser;
    private File arquivoAtual = null;
    
    /**
     * Creates new form CMMCompilerFrame
     */
    public CMMCompilerFrame() {
        initComponents();
        initCustomComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnCompilar = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        pnlEditorContainer = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTokens = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mniAbrir = new javax.swing.JMenuItem();
        mniSalvar = new javax.swing.JMenuItem();
        mniSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCompilar.setText("Compilar");
        btnCompilar.setFocusable(false);
        btnCompilar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCompilar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCompilar.addActionListener(this::btnCompilarActionPerformed);
        jToolBar1.add(btnCompilar);

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        pnlEditorContainer.setMinimumSize(new java.awt.Dimension(300, 300));

        javax.swing.GroupLayout pnlEditorContainerLayout = new javax.swing.GroupLayout(pnlEditorContainer);
        pnlEditorContainer.setLayout(pnlEditorContainerLayout);
        pnlEditorContainerLayout.setHorizontalGroup(
            pnlEditorContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 768, Short.MAX_VALUE)
        );
        pnlEditorContainerLayout.setVerticalGroup(
            pnlEditorContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jSplitPane1.setLeftComponent(pnlEditorContainer);

        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(300, 300));

        tblTokens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Linha", "Coluna", "Tipo", "Lexema", "Valor"
            }
        ));
        jScrollPane1.setViewportView(tblTokens);

        jTabbedPane1.addTab("Tokens", jScrollPane1);

        jSplitPane1.setRightComponent(jTabbedPane1);

        jMenu1.setText("File");

        mniAbrir.setText("Abrir");
        mniAbrir.addActionListener(this::mniAbrirActionPerformed);
        jMenu1.add(mniAbrir);

        mniSalvar.setText("Salvar");
        mniSalvar.addActionListener(this::mniSalvarActionPerformed);
        jMenu1.add(mniSalvar);

        mniSair.setText("Sair");
        mniSair.addActionListener(this::mniSairActionPerformed);
        jMenu1.add(mniSair);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAbrirActionPerformed
        acaoAbrir();
    }//GEN-LAST:event_mniAbrirActionPerformed

    private void btnCompilarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompilarActionPerformed
        acaoCompilar();
    }//GEN-LAST:event_btnCompilarActionPerformed

    private void mniSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSalvarActionPerformed
        acaoSalvar();
    }//GEN-LAST:event_mniSalvarActionPerformed

    private void mniSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mniSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CMMCompilerFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCompilar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem mniAbrir;
    private javax.swing.JMenuItem mniSair;
    private javax.swing.JMenuItem mniSalvar;
    private javax.swing.JPanel pnlEditorContainer;
    private javax.swing.JTable tblTokens;
    // End of variables declaration//GEN-END:variables

/**
     * Inicializa o editor de código e configurações manuais
     */
    private void initCustomComponents() {
        // Configurações da Janela
        this.setLocationRelativeTo(null);
        this.setTitle("IDE C-- Compiler - Sem Título");

        // Criando o Editor de Código (RSyntaxTextArea)
        textArea = new RSyntaxTextArea(20, 60);
        textArea.setSyntaxEditingStyle(SyntaxConstants.SYNTAX_STYLE_C);
        textArea.setCodeFoldingEnabled(true);
        textArea.setAntiAliasingEnabled(true);
        textArea.setFont(new java.awt.Font("Consolas", java.awt.Font.PLAIN, 14));
        
        // Conectando o Lexer (Parser)
        lexerParser = new LexerParser();
        textArea.addParser(lexerParser);

        // Adicionando Scroll e colocando dentro do painel que criamos no Design
        RTextScrollPane scrollPane = new RTextScrollPane(textArea);
        scrollPane.setFoldIndicatorEnabled(true);
        
        // pnlEditorContainer é o nome do JPanel que você criou no passo 2
        pnlEditorContainer.setLayout(new BorderLayout());
        pnlEditorContainer.add(scrollPane, BorderLayout.CENTER);
        
        // Configura a tabela para pintar erros de vermelho
        configurarRenderizacaoTabela();
    }
    
    private void configurarRenderizacaoTabela() {
        // tblTokens é o nome da JTable que você criou no passo 2
        tblTokens.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                
                // Pega o valor da coluna "Tipo" (índice 2)
                Object tipoVal = table.getValueAt(row, 2);
                String tipo = (tipoVal != null) ? tipoVal.toString() : "";
                
                if ("ERROR".equals(tipo)) {
                    c.setForeground(Color.RED);
                    c.setFont(c.getFont().deriveFont(java.awt.Font.BOLD));
                } else {
                    c.setForeground(Color.BLACK);
                }
                return c;
            }
        });
    }

    private void atualizarTabelaTokens() {
        textArea.forceReparsing(0);
        List<Token> tokens = lexerParser.getLastTokens();
        
        DefaultTableModel model = (DefaultTableModel) tblTokens.getModel();
        model.setRowCount(0); // Limpa tabela
        
        // Garante que as colunas existem (caso você não tenha criado no design)
        if (model.getColumnCount() == 0) {
            model.addColumn("Linha");
            model.addColumn("Coluna");
            model.addColumn("Tipo");
            model.addColumn("Lexema");
            model.addColumn("Valor");
        }
        
        for (Token t : tokens) {
            model.addRow(new Object[]{
                t.getLine(),
                t.getColumn(),
                t.getType(),
                t.getLexeme(),
                t.getLiteral()
            });
        }
    }

    // --- Métodos de Ação (Chame estes nos eventos dos botões) ---

    private void acaoCompilar() {
        atualizarTabelaTokens();
    }

    private void acaoAbrir() {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter(new FileNameExtensionFilter("Arquivos C-- (*.cmm, *.txt)", "cmm", "txt"));
        
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            try {
                String content = Files.readString(selectedFile.toPath());
                textArea.setText(content);
                textArea.setCaretPosition(0);
                
                arquivoAtual = selectedFile;
                setTitle("IDE C-- Compiler - " + selectedFile.getName());
                
                atualizarTabelaTokens();
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Erro ao ler arquivo: " + ex.getMessage());
            }
        }
    }

    private void acaoSalvar() {
        if (arquivoAtual == null) {
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setFileFilter(new FileNameExtensionFilter("Arquivos C-- (*.cmm)", "cmm"));
            
            int result = fileChooser.showSaveDialog(this);
            if (result == JFileChooser.APPROVE_OPTION) {
                File fileToSave = fileChooser.getSelectedFile();
                if (!fileToSave.getName().toLowerCase().endsWith(".cmm")) {
                    fileToSave = new File(fileToSave.getAbsolutePath() + ".cmm");
                }
                arquivoAtual = fileToSave;
            } else {
                return;
            }
        }
        try {
            Files.writeString(arquivoAtual.toPath(), textArea.getText());
            setTitle("IDE C-- Compiler - " + arquivoAtual.getName());
            JOptionPane.showMessageDialog(this, "Salvo com sucesso!");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao salvar: " + ex.getMessage());
        }
    }
}
