/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cmm.compiler.view;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import com.mycompany.cmm.compiler.view.LexerParser;
import com.mycompany.cmm.compiler.model.Token;
import com.mycompany.cmm.compiler.model.SymbolInfo;
import com.mycompany.cmm.compiler.model.TokenType;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import org.fife.ui.rsyntaxtextarea.RSyntaxTextArea;
import org.fife.ui.rsyntaxtextarea.SyntaxConstants;
import org.fife.ui.rtextarea.RTextScrollPane;
import javax.swing.Timer;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author caiof
 */
public class CMMCompilerFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CMMCompilerFrame.class.getName());
    
    private RSyntaxTextArea textArea;
    private LexerParser lexerParser;
    private File arquivoAtual = null;
    
    /**
     * Creates new form CMMCompilerFrame
     */
    public CMMCompilerFrame() {
        initComponents();
        initCustomComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        pnlEditorContainer = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTokens = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtOutput = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mniNovo = new javax.swing.JMenuItem();
        mniAbrir = new javax.swing.JMenuItem();
        mniSalvar = new javax.swing.JMenuItem();
        mniSair = new javax.swing.JMenuItem();
        mnuCompilar = new javax.swing.JMenu();
        mniCompilarAgora = new javax.swing.JMenuItem();
        mniAutoCompilar = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        pnlEditorContainer.setMinimumSize(new java.awt.Dimension(300, 300));

        javax.swing.GroupLayout pnlEditorContainerLayout = new javax.swing.GroupLayout(pnlEditorContainer);
        pnlEditorContainer.setLayout(pnlEditorContainerLayout);
        pnlEditorContainerLayout.setHorizontalGroup(
            pnlEditorContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 768, Short.MAX_VALUE)
        );
        pnlEditorContainerLayout.setVerticalGroup(
            pnlEditorContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jSplitPane1.setLeftComponent(pnlEditorContainer);

        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(300, 300));

        tblTokens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Linha", "Coluna", "Tipo", "Lexema", "Valor"
            }
        ));
        jScrollPane1.setViewportView(tblTokens);

        jTabbedPane1.addTab("Tokens", jScrollPane1);

        txtOutput.setEditable(false);
        txtOutput.setColumns(20);
        txtOutput.setRows(5);
        jScrollPane2.setViewportView(txtOutput);

        jTabbedPane1.addTab("Output", jScrollPane2);

        jSplitPane1.setRightComponent(jTabbedPane1);

        jMenu1.setText("File");

        mniNovo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniNovo.setText("Novo");
        mniNovo.addActionListener(this::mniNovoActionPerformed);
        jMenu1.add(mniNovo);

        mniAbrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniAbrir.setText("Abrir");
        mniAbrir.addActionListener(this::mniAbrirActionPerformed);
        jMenu1.add(mniAbrir);

        mniSalvar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniSalvar.setText("Salvar");
        mniSalvar.addActionListener(this::mniSalvarActionPerformed);
        jMenu1.add(mniSalvar);

        mniSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniSair.setText("Sair");
        mniSair.addActionListener(this::mniSairActionPerformed);
        jMenu1.add(mniSair);

        jMenuBar1.add(jMenu1);

        mnuCompilar.setText("Compile");

        mniCompilarAgora.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniCompilarAgora.setText("Compilar");
        mniCompilarAgora.addActionListener(this::mniCompilarAgoraActionPerformed);
        mnuCompilar.add(mniCompilarAgora);

        mniAutoCompilar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniAutoCompilar.setSelected(true);
        mniAutoCompilar.setText("Compilar Automatico");
        mnuCompilar.add(mniAutoCompilar);

        jMenuBar1.add(mnuCompilar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAbrirActionPerformed
        acaoAbrir();
    }//GEN-LAST:event_mniAbrirActionPerformed

    private void mniSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSalvarActionPerformed
        acaoSalvar();
    }//GEN-LAST:event_mniSalvarActionPerformed

    private void mniSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mniSairActionPerformed

    private void mniCompilarAgoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCompilarAgoraActionPerformed
        acaoCompilar();
    }//GEN-LAST:event_mniCompilarAgoraActionPerformed

    private void mniNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniNovoActionPerformed
        acaoNovo();
    }//GEN-LAST:event_mniNovoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CMMCompilerFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JMenuItem mniAbrir;
    private javax.swing.JCheckBoxMenuItem mniAutoCompilar;
    private javax.swing.JMenuItem mniCompilarAgora;
    private javax.swing.JMenuItem mniNovo;
    private javax.swing.JMenuItem mniSair;
    private javax.swing.JMenuItem mniSalvar;
    private javax.swing.JMenu mnuCompilar;
    private javax.swing.JPanel pnlEditorContainer;
    private javax.swing.JTable tblTokens;
    private javax.swing.JTextArea txtOutput;
    // End of variables declaration//GEN-END:variables

    /**
     * Inicializa o editor de código e configurações manuais
     */
    private void initCustomComponents() {
        this.setLocationRelativeTo(null);
        this.setTitle("IDE C-- Compiler - Sem Título");

        textArea = new RSyntaxTextArea(20, 60);
        textArea.setSyntaxEditingStyle(SyntaxConstants.SYNTAX_STYLE_C);
        textArea.setCodeFoldingEnabled(true);
        textArea.setAntiAliasingEnabled(true);
        textArea.setFont(new java.awt.Font("Consolas", java.awt.Font.PLAIN, 14));
        
        lexerParser = new LexerParser();
        textArea.addParser(lexerParser);

        RTextScrollPane scrollPane = new RTextScrollPane(textArea);
        scrollPane.setFoldIndicatorEnabled(true);
        
        pnlEditorContainer.setLayout(new BorderLayout());
        pnlEditorContainer.add(scrollPane, BorderLayout.CENTER);
        
        configurarRenderizacaoTabela();
        
        Timer timerCompilacao = new Timer(700, e -> atualizarTabelaTokens());
        timerCompilacao.setRepeats(false);

        textArea.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) { verificarECompilar(); }
            @Override
            public void removeUpdate(DocumentEvent e) { verificarECompilar(); }
            @Override
            public void changedUpdate(DocumentEvent e) { verificarECompilar(); }

            private void verificarECompilar() {
                if (mniAutoCompilar.isSelected()) {
                    timerCompilacao.restart();
                }
            }
        });
    }
    
    private void configurarRenderizacaoTabela() {
        tblTokens.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

                Object tipoVal = table.getValueAt(row, 2);
                String tipo = (tipoVal != null) ? tipoVal.toString() : "";

                if ("ERROR".equals(tipo)) {
                    c.setForeground(Color.RED);
                    c.setFont(c.getFont().deriveFont(java.awt.Font.BOLD));
                } else {
                    c.setForeground(Color.BLACK);
                }

                Object valorVal = table.getValueAt(row, 4);
                String valor = (valorVal != null) ? valorVal.toString() : "";
                if (valor.startsWith("ERRO:")) {
                    c.setForeground(Color.RED);
                }

                return c;
            }
        });
    }

    private void atualizarTabelaTokens() {
        try {
            textArea.forceReparsing(0);
            List<Token> tokens = lexerParser.getLastTokens();

            DefaultTableModel model = (DefaultTableModel) tblTokens.getModel();
            model.setRowCount(0);

            if (model.getColumnCount() == 0) {
                model.addColumn("Linha");
                model.addColumn("Coluna");
                model.addColumn("Tipo");
                model.addColumn("Lexema");
                model.addColumn("Valor");
            }

            StringBuilder outputMsg = new StringBuilder();
            StringBuilder runtimeOut = new StringBuilder();
            int errorCount = 0;

            for (int i = 0; i < tokens.size(); i++) {
                Token t = tokens.get(i);
                String valorColuna = "";
                
                if (t.getType() == TokenType.ERROR) {
                    outputMsg.append("Erro Léxico [Linha ").append(t.getLine())
                             .append("]: Token/Caractere inválido '").append(t.getLexeme()).append("'\n");
                    errorCount++;
                }

                if (t.getType() == TokenType.ID) {
                    boolean isDeclaration = false;
                    if (i > 0) {
                        TokenType prev = tokens.get(i - 1).getType();
                        if (prev == TokenType.INT || prev == TokenType.VOID || 
                            prev == TokenType.FLOAT || prev == TokenType.CHAR) {
                            isDeclaration = true;
                        }
                    }
                } else if (t.getType() == TokenType.PRINTF) {
                    // If printf has a single simple argument (literal/number/identifier), append it to output
                    int j = i + 1;
                    if (j < tokens.size() && tokens.get(j).getType() == TokenType.LPAREN) {
                        int k = j + 1;
                        int depth = 1;
                        java.util.List<Token> args = new java.util.ArrayList<>();
                        while (k < tokens.size() && depth > 0) {
                            Token tk = tokens.get(k);
                            if (tk.getType() == TokenType.LPAREN) depth++;
                            else if (tk.getType() == TokenType.RPAREN) depth--;
                            if (depth > 0) args.add(tk);
                            k++;
                        }

                        if (args.size() == 1) {
                            Token arg = args.get(0);
                            if (arg.getType() == TokenType.LITERAL || arg.getType() == TokenType.NUMBER_INT || arg.getType() == TokenType.NUMBER_FLOAT) {
                                runtimeOut.append(arg.getLexeme()).append("\n");
                            } 
                        }
                    }
                } else if (t.getLiteral() != null) {
                    valorColuna = t.getLiteral().toString();
                }

                model.addRow(new Object[]{
                    t.getLine(),
                    t.getColumn(),
                    t.getType(),
                    t.getLexeme(),
                    valorColuna
                });
            }
            
            if (errorCount == 0) {
                txtOutput.setForeground(new Color(0, 150, 0));
                if (runtimeOut.length() > 0) {
                    txtOutput.setText("Compilação concluída com sucesso.\n\nSaída:\n" + runtimeOut.toString());
                } else {
                    txtOutput.setText("Compilação concluída com sucesso.\nNenhum erro encontrado.");
                }
            } else {
                txtOutput.setForeground(Color.RED);
                txtOutput.setText(String.format("Falha na compilação. %d erro(s) encontrado(s):\n\n", errorCount));
                txtOutput.append(outputMsg.toString());
                if (runtimeOut.length() > 0) {
                    txtOutput.append("\nSaída:\n");
                    txtOutput.append(runtimeOut.toString());
                }
            }

        } catch (Exception e) {
            System.out.println("Erro ao atualizar tokens: " + e.getMessage());
            e.printStackTrace(); 
        }
    }

    private void acaoCompilar() {
        // Do not overwrite the editor contents when compiling — preserve user's formatting.
        // Previously we normalized whitespace and replaced the editor text here, which
        // could remove comments, preprocessor directives and original line breaks.
        atualizarTabelaTokens();
    }

    private String normalizeWhitespace(String code) {
        String s = code.replaceAll("\\s+", " ").trim();

        s = s.replace("{", "{ ").replace("}", "} ");
        s = s.replaceAll(" {2,}", " ").trim();

        java.util.List<String> tokens = new java.util.ArrayList<>();
        StringBuilder cur = new StringBuilder();
        for (String part : s.split(" ")) {
            if (part.isEmpty()) continue;
            if (cur.length() > 0) cur.append(' ');
            cur.append(part);
            if (part.equals("{") || part.equals("}") || part.equals(";")) {
                tokens.add(cur.toString().trim());
                cur.setLength(0);
            }
        }
        if (cur.length() > 0) tokens.add(cur.toString().trim());

        StringBuilder out = new StringBuilder();
        int indent = 0;
        for (String tok : tokens) {
            String t = tok.trim();
            if (t.equals("}")) {
                indent = Math.max(0, indent - 1);
                out.append("  ".repeat(indent)).append("}").append("\n");
            } else if (t.endsWith("{")) {
                String header = t.substring(0, t.length() - 1).trim();
                if (!header.isEmpty()) {
                    out.append("  ".repeat(indent)).append(header).append(" {").append("\n");
                } else {
                    out.append("  ".repeat(indent)).append("{").append("\n");
                }
                indent++;
            } else {
                out.append("  ".repeat(indent)).append(t).append("\n");
            }
        }

        if (!out.toString().endsWith("\n")) out.append("\n");
        return out.toString();
    }

    private void acaoAbrir() {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter(new FileNameExtensionFilter("Arquivos C-- (*.cmm, *.txt)", "cmm", "txt"));
        
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            try {
                String content = Files.readString(selectedFile.toPath());
                textArea.setText(content);
                textArea.setCaretPosition(0);
                
                arquivoAtual = selectedFile;
                setTitle("IDE C-- Compiler - " + selectedFile.getName());
                
                atualizarTabelaTokens();
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Erro ao ler arquivo: " + ex.getMessage());
            }
        }
    }

    private void acaoSalvar() {
        if (arquivoAtual == null) {
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setFileFilter(new FileNameExtensionFilter("Arquivos C-- (*.cmm)", "cmm"));
            
            int result = fileChooser.showSaveDialog(this);
            if (result == JFileChooser.APPROVE_OPTION) {
                File fileToSave = fileChooser.getSelectedFile();
                if (!fileToSave.getName().toLowerCase().endsWith(".cmm")) {
                    fileToSave = new File(fileToSave.getAbsolutePath() + ".cmm");
                }
                arquivoAtual = fileToSave;
            } else {
                return;
            }
        }
        try {
            Files.writeString(arquivoAtual.toPath(), textArea.getText());
            setTitle("IDE C-- Compiler - " + arquivoAtual.getName());
            JOptionPane.showMessageDialog(this, "Salvo com sucesso!");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao salvar: " + ex.getMessage());
        }
    }
            
    private void acaoNovo() {
        if (textArea.getText().length() > 0) {
            int response = JOptionPane.showConfirmDialog(this, 
                "Deseja salvar o arquivo atual antes de criar um novo?", 
                "Novo Arquivo", 
                JOptionPane.YES_NO_CANCEL_OPTION);
            
            if (response == JOptionPane.CANCEL_OPTION) return;
            if (response == JOptionPane.YES_OPTION) acaoSalvar();
        }

        textArea.setText("");
        arquivoAtual = null;
        setTitle("IDE C-- Compiler - Sem Título");
        
        DefaultTableModel model = (DefaultTableModel) tblTokens.getModel();
        model.setRowCount(0);
    }       
}
